# Generated by Django 5.1.4 on 2024-12-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_task_user_subtask_task_users_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_contacts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('userStory', 'User Story'), ('', 'No Category')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=7),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
