# Generated by Django 5.1.4 on 2024-12-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0007_remove_task_subtask_task_subtasks_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(),
        ),
    ]
