# Generated by Django 5.1.4 on 2024-12-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0012_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_contacts',
            new_name='assignedContacts',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
