# Generated by Django 5.1.4 on 2024-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0013_rename_assigned_contacts_task_assignedcontacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
