# Generated by Django 5.1.4 on 2025-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0017_alter_subtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(default='in-progress', max_length=20),
        ),
    ]
