# Generated by Django 5.1.4 on 2025-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0019_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inProgress', 'In Progress'), ('awaitFeedback', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=13),
        ),
    ]
