# Generated by Django 5.1.4 on 2025-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0021_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('User_Story', 'User Story')], default='', max_length=10),
        ),
    ]
