# Generated by Django 5.1.4 on 2025-01-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0023_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
